### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by almos98** [tati-z/Whiteboard#1]
The [link](https://docs.google.com/document/d/10_gwtNKcPI7r_pmcKxcnZtuWOah5rcaTTEH9aVbfZic) for app evolution requires me to request access, but I believe it should be public

**Comment by tati-z** [comment]
Nice catch 💯, it was the G Suite restrictions from using college email, just fixed it in 
https://github.com/tati-z/Whiteboard/commit/80e5bd81b6c8a7e4b6b7214a2745791435026321
